//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18051
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenieWP8.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenieWP8.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许在网络中播放 的本地化字符串。
        /// </summary>
        public static string AllowPlayInNetworkText {
            get {
                return ResourceManager.GetString("AllowPlayInNetworkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亚马逊Kindle 的本地化字符串。
        /// </summary>
        public static string amazonkindledev {
            get {
                return ResourceManager.GetString("amazonkindledev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Android 设备 的本地化字符串。
        /// </summary>
        public static string androiddevice {
            get {
                return ResourceManager.GetString("androiddevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Android 手机 的本地化字符串。
        /// </summary>
        public static string androidphone {
            get {
                return ResourceManager.GetString("androidphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Android 平板电脑 的本地化字符串。
        /// </summary>
        public static string androidtablet {
            get {
                return ResourceManager.GetString("androidtablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单项 的本地化字符串。
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的应用程序 的本地化字符串。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均 的本地化字符串。
        /// </summary>
        public static string AverageText {
            get {
                return ResourceManager.GetString("AverageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败。请重新输入NETGEAR路由器的正确管理员密码。 的本地化字符串。
        /// </summary>
        public static string bad_password {
            get {
                return ResourceManager.GetString("bad_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蓝牙播放器 的本地化字符串。
        /// </summary>
        public static string blurayplayer {
            get {
                return ResourceManager.GetString("blurayplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网桥 的本地化字符串。
        /// </summary>
        public static string bridge {
            get {
                return ResourceManager.GetString("bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        public static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件 的本地化字符串。
        /// </summary>
        public static string btnFileUpload {
            get {
                return ResourceManager.GetString("btnFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string btnModify {
            get {
                return ResourceManager.GetString("btnModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是什么？ 的本地化字符串。
        /// </summary>
        public static string btnWhat {
            get {
                return ResourceManager.GetString("btnWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bypass 的本地化字符串。
        /// </summary>
        public static string BypassText {
            get {
                return ResourceManager.GetString("BypassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线缆 STB 的本地化字符串。
        /// </summary>
        public static string cablestb {
            get {
                return ResourceManager.GetString("cablestb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机 的本地化字符串。
        /// </summary>
        public static string cameradev {
            get {
                return ResourceManager.GetString("cameradev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string CancelButtonContent {
            get {
                return ResourceManager.GetString("CancelButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改定制的设置 的本地化字符串。
        /// </summary>
        public static string ChangeCustomizingSettingText {
            get {
                return ResourceManager.GetString("ChangeCustomizingSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频道 的本地化字符串。
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频道 的本地化字符串。
        /// </summary>
        public static string ChannelPageTitleText {
            get {
                return ResourceManager.GetString("ChannelPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查可用性 的本地化字符串。
        /// </summary>
        public static string CheckAvailabilityContent {
            get {
                return ResourceManager.GetString("CheckAvailabilityContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访客访问 的本地化字符串。
        /// </summary>
        public static string CheckGuestAccessText {
            get {
                return ResourceManager.GetString("CheckGuestAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 家长控制 的本地化字符串。
        /// </summary>
        public static string CheckParentalControlText {
            get {
                return ResourceManager.GetString("CheckParentalControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流量控制 的本地化字符串。
        /// </summary>
        public static string CheckTrafficMeterText {
            get {
                return ResourceManager.GetString("CheckTrafficMeterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string CloseAboutButtonContent {
            get {
                return ResourceManager.GetString("CloseAboutButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string CloseLicenseButtonContent {
            get {
                return ResourceManager.GetString("CloseLicenseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您已经成功设置了由OpenDNS提供支持的NETGEAR实时家长控制。下次运行管理工具时，它会带您到状态页，您可以： 的本地化字符串。
        /// </summary>
        public static string CompleteIllustrationText {
            get {
                return ResourceManager.GetString("CompleteIllustrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认电子邮件 的本地化字符串。
        /// </summary>
        public static string ConfirmEmailText {
            get {
                return ResourceManager.GetString("ConfirmEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string ConfirmPasswordText {
            get {
                return ResourceManager.GetString("ConfirmPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright (c) 2013, NETGEAR Inc. 的本地化字符串。
        /// </summary>
        public static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计数器启动时间 的本地化字符串。
        /// </summary>
        public static string CounterStartTime {
            get {
                return ResourceManager.GetString("CounterStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动时间-时 的本地化字符串。
        /// </summary>
        public static string CounterStartTimeHour {
            get {
                return ResourceManager.GetString("CounterStartTimeHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动时间-分 的本地化字符串。
        /// </summary>
        public static string CounterStartTimeMin {
            get {
                return ResourceManager.GetString("CounterStartTimeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 的本地化字符串。
        /// </summary>
        public static string DownloadText {
            get {
                return ResourceManager.GetString("DownloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DVR 的本地化字符串。
        /// </summary>
        public static string dvr {
            get {
                return ResourceManager.GetString("dvr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件 的本地化字符串。
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要设置实时家长控制，您需要拥有OpenDNS账户。已经有账户了吗？ 的本地化字符串。
        /// </summary>
        public static string EnquireOpenDNSText {
            get {
                return ResourceManager.GetString("EnquireOpenDNSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入以下信息。 的本地化字符串。
        /// </summary>
        public static string EnterRegInformationText {
            get {
                return ResourceManager.GetString("EnterRegInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入下面的用户名和密码。 的本地化字符串。
        /// </summary>
        public static string EnterUsername_PasswordText {
            get {
                return ResourceManager.GetString("EnterUsername_PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤级别 的本地化字符串。
        /// </summary>
        public static string FilterLevel {
            get {
                return ResourceManager.GetString("FilterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有连接到您路由器上的计算机都将受您选择的以下内容保护。您可以稍后通过我们的网站定制您的实时家长控制。 的本地化字符串。
        /// </summary>
        public static string FiltingIllustrationText {
            get {
                return ResourceManager.GetString("FiltingIllustrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固件版本： 的本地化字符串。
        /// </summary>
        public static string FirmwareVersionText {
            get {
                return ResourceManager.GetString("FirmwareVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏控制台 的本地化字符串。
        /// </summary>
        public static string gamedev {
            get {
                return ResourceManager.GetString("gamedev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由器 的本地化字符串。
        /// </summary>
        public static string gatewaydev {
            get {
                return ResourceManager.GetString("gatewaydev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访客访问 的本地化字符串。
        /// </summary>
        public static string GuestAccess {
            get {
                return ResourceManager.GetString("GuestAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访客访问 的本地化字符串。
        /// </summary>
        public static string GuestAccessPageTitleText {
            get {
                return ResourceManager.GetString("GuestAccessPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全 的本地化字符串。
        /// </summary>
        public static string GuestSecurityPageTitleText {
            get {
                return ResourceManager.GetString("GuestSecurityPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访客设置 的本地化字符串。
        /// </summary>
        public static string GuestSettingPageTitleText {
            get {
                return ResourceManager.GetString("GuestSettingPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间段 的本地化字符串。
        /// </summary>
        public static string GuestTimeSegPageTitleText {
            get {
                return ResourceManager.GetString("GuestTimeSegPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称/无线网络标识 的本地化字符串。
        /// </summary>
        public static string GuestWiFiName {
            get {
                return ResourceManager.GetString("GuestWiFiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阻止所有与成人有关的网站、非法活动、社交网站、共享视频网站、钓鱼网站以及浪费时间的内容。 的本地化字符串。
        /// </summary>
        public static string Illustration_HighText {
            get {
                return ResourceManager.GetString("Illustration_HighText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阻止情色网站和网络钓鱼。 的本地化字符串。
        /// </summary>
        public static string Illustration_LowText {
            get {
                return ResourceManager.GetString("Illustration_LowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阻止所有与成人有关的网站、非法活动和网络钓鱼。 的本地化字符串。
        /// </summary>
        public static string Illustration_MediumText {
            get {
                return ResourceManager.GetString("Illustration_MediumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅阻止网络钓鱼。 的本地化字符串。
        /// </summary>
        public static string Illustration_MinimumText {
            get {
                return ResourceManager.GetString("Illustration_MinimumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不阻止。 的本地化字符串。
        /// </summary>
        public static string Illustration_NoneText {
            get {
                return ResourceManager.GetString("Illustration_NoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *  检查实时家长控制是否已经启动 的本地化字符串。
        /// </summary>
        public static string Illustration1Text {
            get {
                return ResourceManager.GetString("Illustration1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *  关闭或启动实时家长控制 的本地化字符串。
        /// </summary>
        public static string Illustration2Text {
            get {
                return ResourceManager.GetString("Illustration2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *  修改基本设置 的本地化字符串。
        /// </summary>
        public static string Illustration3Text {
            get {
                return ResourceManager.GetString("Illustration3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *  更改定制的设置，如基于实时家长控制的各用户或每天的特定时间 的本地化字符串。
        /// </summary>
        public static string Illustration4Text {
            get {
                return ResourceManager.GetString("Illustration4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 iMac 的本地化字符串。
        /// </summary>
        public static string imacdev {
            get {
                return ResourceManager.GetString("imacdev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 因特网不可用。请先将路由器连接到因特网。 的本地化字符串。
        /// </summary>
        public static string interneterror {
            get {
                return ResourceManager.GetString("interneterror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 iPad 的本地化字符串。
        /// </summary>
        public static string ipad {
            get {
                return ResourceManager.GetString("ipad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 iPad Mini 的本地化字符串。
        /// </summary>
        public static string ipadmini {
            get {
                return ResourceManager.GetString("ipadmini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 iPhone 的本地化字符串。
        /// </summary>
        public static string iphone {
            get {
                return ResourceManager.GetString("iphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 iPhone5 的本地化字符串。
        /// </summary>
        public static string iphone5 {
            get {
                return ResourceManager.GetString("iphone5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 iPod Touch 的本地化字符串。
        /// </summary>
        public static string ipodtouch {
            get {
                return ResourceManager.GetString("ipodtouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密钥/密码 的本地化字符串。
        /// </summary>
        public static string Key_Password {
            get {
                return ResourceManager.GetString("Key_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上个月 的本地化字符串。
        /// </summary>
        public static string LastMonthAvgText {
            get {
                return ResourceManager.GetString("LastMonthAvgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上个月 的本地化字符串。
        /// </summary>
        public static string LastMonthTotalText {
            get {
                return ResourceManager.GetString("LastMonthTotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 许可 的本地化字符串。
        /// </summary>
        public static string LicenseButtonContent {
            get {
                return ResourceManager.GetString("LicenseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 许可 的本地化字符串。
        /// </summary>
        public static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每月限制(MB) 的本地化字符串。
        /// </summary>
        public static string LimitPerMonth {
            get {
                return ResourceManager.GetString("LimitPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linux PC 的本地化字符串。
        /// </summary>
        public static string linuxpc {
            get {
                return ResourceManager.GetString("linuxpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败！请检查本计算机是否已连接到 NETGEAR 路由器。 的本地化字符串。
        /// </summary>
        public static string login_alertinfo {
            get {
                return ResourceManager.GetString("login_alertinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string LoginButtonContent {
            get {
                return ResourceManager.GetString("LoginButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string LoginPageTitleText {
            get {
                return ResourceManager.GetString("LoginPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        public static string LogoutButtonContent {
            get {
                return ResourceManager.GetString("LogoutButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MacBook 的本地化字符串。
        /// </summary>
        public static string macbookdev {
            get {
                return ResourceManager.GetString("macbookdev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mac Mini 的本地化字符串。
        /// </summary>
        public static string macminidev {
            get {
                return ResourceManager.GetString("macminidev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mac Pro 的本地化字符串。
        /// </summary>
        public static string macprodev {
            get {
                return ResourceManager.GetString("macprodev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MarketPlace 的本地化字符串。
        /// </summary>
        public static string MarketPlace {
            get {
                return ResourceManager.GetString("MarketPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 兆字节 的本地化字符串。
        /// </summary>
        public static string MbytesText {
            get {
                return ResourceManager.GetString("MbytesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体设备 的本地化字符串。
        /// </summary>
        public static string mediadev {
            get {
                return ResourceManager.GetString("mediadev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能手机 的本地化字符串。
        /// </summary>
        public static string mobiledev {
            get {
                return ResourceManager.GetString("mobiledev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本月 的本地化字符串。
        /// </summary>
        public static string MonthAvgText {
            get {
                return ResourceManager.GetString("MonthAvgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本月 的本地化字符串。
        /// </summary>
        public static string MonthTotalText {
            get {
                return ResourceManager.GetString("MonthTotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的媒体 的本地化字符串。
        /// </summary>
        public static string MyMedia {
            get {
                return ResourceManager.GetString("MyMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项 的本地化字符串。
        /// </summary>
        public static string MyMediaOption {
            get {
                return ResourceManager.GetString("MyMediaOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项 的本地化字符串。
        /// </summary>
        public static string MyMediaOptionPageTitleText {
            get {
                return ResourceManager.GetString("MyMediaOptionPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的媒体 的本地化字符串。
        /// </summary>
        public static string MyMediaPageTitleText {
            get {
                return ResourceManager.GetString("MyMediaPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放器 的本地化字符串。
        /// </summary>
        public static string MyMediaPlayer {
            get {
                return ResourceManager.GetString("MyMediaPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放器 的本地化字符串。
        /// </summary>
        public static string MyMediaPlayerPageTitleText {
            get {
                return ResourceManager.GetString("MyMediaPlayerPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在播放 的本地化字符串。
        /// </summary>
        public static string MyMediaPlaying {
            get {
                return ResourceManager.GetString("MyMediaPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在播放 的本地化字符串。
        /// </summary>
        public static string MyMediaPlayingPageTitleText {
            get {
                return ResourceManager.GetString("MyMediaPlayingPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来源 的本地化字符串。
        /// </summary>
        public static string MyMediaSource {
            get {
                return ResourceManager.GetString("MyMediaSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来源 的本地化字符串。
        /// </summary>
        public static string MyMediaSourcePageTitleText {
            get {
                return ResourceManager.GetString("MyMediaSourcePageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储 的本地化字符串。
        /// </summary>
        public static string netstoragedev {
            get {
                return ResourceManager.GetString("netstoragedev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络设备 的本地化字符串。
        /// </summary>
        public static string networkdev {
            get {
                return ResourceManager.GetString("networkdev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络映射 的本地化字符串。
        /// </summary>
        public static string NetworkMap {
            get {
                return ResourceManager.GetString("NetworkMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络映射 的本地化字符串。
        /// </summary>
        public static string NetworkMapPageTitleText {
            get {
                return ResourceManager.GetString("NetworkMapPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一步 的本地化字符串。
        /// </summary>
        public static string NextButtonContent {
            get {
                return ResourceManager.GetString("NextButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string NoButtonContent {
            get {
                return ResourceManager.GetString("NoButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在无线网络设置有更改时重新启动媒体服务。 的本地化字符串。
        /// </summary>
        public static string NoteContentText {
            get {
                return ResourceManager.GetString("NoteContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意： 的本地化字符串。
        /// </summary>
        public static string NoteText {
            get {
                return ResourceManager.GetString("NoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由器不支持该功能。 的本地化字符串。
        /// </summary>
        public static string notsupport {
            get {
                return ResourceManager.GetString("notsupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenDNS 账户 的本地化字符串。
        /// </summary>
        public static string OpenDNSUserText {
            get {
                return ResourceManager.GetString("OpenDNSUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 家长控制 的本地化字符串。
        /// </summary>
        public static string ParentalControl {
            get {
                return ResourceManager.GetString("ParentalControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 家长控制 的本地化字符串。
        /// </summary>
        public static string ParentalControlPageTitleText {
            get {
                return ResourceManager.GetString("ParentalControlPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （默认值为“password”） 的本地化字符串。
        /// </summary>
        public static string PasswordTipsText {
            get {
                return ResourceManager.GetString("PasswordTipsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一步 的本地化字符串。
        /// </summary>
        public static string PreviousButtonContent {
            get {
                return ResourceManager.GetString("PreviousButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印机 的本地化字符串。
        /// </summary>
        public static string printerdev {
            get {
                return ResourceManager.GetString("printerdev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐私权政策 的本地化字符串。
        /// </summary>
        public static string PrivacyPolicyContent {
            get {
                return ResourceManager.GetString("PrivacyPolicyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QR码 的本地化字符串。
        /// </summary>
        public static string QRCode {
            get {
                return ResourceManager.GetString("QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QR码 的本地化字符串。
        /// </summary>
        public static string QRCodePageTitleText {
            get {
                return ResourceManager.GetString("QRCodePageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高 的本地化字符串。
        /// </summary>
        public static string radioButton_HighContent {
            get {
                return ResourceManager.GetString("radioButton_HighContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 低 的本地化字符串。
        /// </summary>
        public static string radioButton_LowContent {
            get {
                return ResourceManager.GetString("radioButton_LowContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中等 的本地化字符串。
        /// </summary>
        public static string radioButton_MediumContent {
            get {
                return ResourceManager.GetString("radioButton_MediumContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小 的本地化字符串。
        /// </summary>
        public static string radioButton_MinimumContent {
            get {
                return ResourceManager.GetString("radioButton_MinimumContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        public static string radioButton_NoneContent {
            get {
                return ResourceManager.GetString("radioButton_NoneContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string RefreshButtonContent {
            get {
                return ResourceManager.GetString("RefreshButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新源文件夹 的本地化字符串。
        /// </summary>
        public static string RefreshSourceFolderText {
            get {
                return ResourceManager.GetString("RefreshSourceFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住密码 的本地化字符串。
        /// </summary>
        public static string RememberPasswordCheckBoxContent {
            get {
                return ResourceManager.GetString("RememberPasswordCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中继器 的本地化字符串。
        /// </summary>
        public static string repeater {
            get {
                return ResourceManager.GetString("repeater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeftToRight 的本地化字符串。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-cn 的本地化字符串。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新启动媒体服务 的本地化字符串。
        /// </summary>
        public static string RestartMediaServiceText {
            get {
                return ResourceManager.GetString("RestartMediaServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回状态页 的本地化字符串。
        /// </summary>
        public static string ReturnButtonContent {
            get {
                return ResourceManager.GetString("ReturnButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版权所有 的本地化字符串。
        /// </summary>
        public static string RightsReservedText {
            get {
                return ResourceManager.GetString("RightsReservedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由器型号： 的本地化字符串。
        /// </summary>
        public static string RouterModelText {
            get {
                return ResourceManager.GetString("RouterModelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 示例运行时属性值 的本地化字符串。
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卫星 STB 的本地化字符串。
        /// </summary>
        public static string satellitestb {
            get {
                return ResourceManager.GetString("satellitestb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描仪 的本地化字符串。
        /// </summary>
        public static string scannerdev {
            get {
                return ResourceManager.GetString("scannerdev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描二维码连接无线网 的本地化字符串。
        /// </summary>
        public static string ScanQrCodeTipsText {
            get {
                return ResourceManager.GetString("ScanQrCodeTipsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全 的本地化字符串。
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string Security_None {
            get {
                return ResourceManager.GetString("Security_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WPA2-PSK[AES] 的本地化字符串。
        /// </summary>
        public static string Security_WPA2PSK_AES {
            get {
                return ResourceManager.GetString("Security_WPA2PSK_AES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WPA-PSK+WPA2-PSK 的本地化字符串。
        /// </summary>
        public static string Security_WPAPSK_WPA2PSK {
            get {
                return ResourceManager.GetString("Security_WPAPSK_WPA2PSK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全 的本地化字符串。
        /// </summary>
        public static string SecurityPageTitleText {
            get {
                return ResourceManager.GetString("SecurityPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置完成 的本地化字符串。
        /// </summary>
        public static string SettingCompleteText {
            get {
                return ResourceManager.GetString("SettingCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑设置 的本地化字符串。
        /// </summary>
        public static string SettingPageTitleText {
            get {
                return ResourceManager.GetString("SettingPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8-63个字符或64位十六进制值 的本地化字符串。
        /// </summary>
        public static string SettingPasswordTipsText {
            get {
                return ResourceManager.GetString("SettingPasswordTipsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在网络中共享文件 的本地化字符串。
        /// </summary>
        public static string ShareFilesInNetworkText {
            get {
                return ResourceManager.GetString("ShareFilesInNetworkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SlingBox 的本地化字符串。
        /// </summary>
        public static string slingbox {
            get {
                return ResourceManager.GetString("slingbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        public static string StartDatePageTitleText {
            get {
                return ResourceManager.GetString("StartDatePageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时 的本地化字符串。
        /// </summary>
        public static string StartTimeHourText {
            get {
                return ResourceManager.GetString("StartTimeHourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分 的本地化字符串。
        /// </summary>
        public static string StartTimeMinuteText {
            get {
                return ResourceManager.GetString("StartTimeMinuteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string StartTimeText {
            get {
                return ResourceManager.GetString("StartTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他 STB 的本地化字符串。
        /// </summary>
        public static string stb {
            get {
                return ResourceManager.GetString("stb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由 SiteView 提供支持 的本地化字符串。
        /// </summary>
        public static string SupportText {
            get {
                return ResourceManager.GetString("SupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交换机 的本地化字符串。
        /// </summary>
        public static string switchdev {
            get {
                return ResourceManager.GetString("switchdev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平板电脑 的本地化字符串。
        /// </summary>
        public static string tablepc {
            get {
                return ResourceManager.GetString("tablepc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条款与条件 的本地化字符串。
        /// </summary>
        public static string Terms_ConditionsText {
            get {
                return ResourceManager.GetString("Terms_ConditionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间段 的本地化字符串。
        /// </summary>
        public static string TimeSegment {
            get {
                return ResourceManager.GetString("TimeSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10 小时 的本地化字符串。
        /// </summary>
        public static string TimeSegment_10hours {
            get {
                return ResourceManager.GetString("TimeSegment_10hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 天 的本地化字符串。
        /// </summary>
        public static string TimeSegment_1day {
            get {
                return ResourceManager.GetString("TimeSegment_1day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 小时 的本地化字符串。
        /// </summary>
        public static string TimeSegment_1hour {
            get {
                return ResourceManager.GetString("TimeSegment_1hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 周 的本地化字符串。
        /// </summary>
        public static string TimeSegment_1week {
            get {
                return ResourceManager.GetString("TimeSegment_1week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5 小时 的本地化字符串。
        /// </summary>
        public static string TimeSegment_5hours {
            get {
                return ResourceManager.GetString("TimeSegment_5hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 永久 的本地化字符串。
        /// </summary>
        public static string TimeSegment_Always {
            get {
                return ResourceManager.GetString("TimeSegment_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天 的本地化字符串。
        /// </summary>
        public static string TodayTotalText {
            get {
                return ResourceManager.GetString("TodayTotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总计 的本地化字符串。
        /// </summary>
        public static string TotalText {
            get {
                return ResourceManager.GetString("TotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用流量统计。要继续吗？ 的本地化字符串。
        /// </summary>
        public static string traffic_disable {
            get {
                return ResourceManager.GetString("traffic_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用流量统计。要继续吗？ 的本地化字符串。
        /// </summary>
        public static string traffic_enable {
            get {
                return ResourceManager.GetString("traffic_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流量限制 的本地化字符串。
        /// </summary>
        public static string TrafficLimitation {
            get {
                return ResourceManager.GetString("TrafficLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅下载 的本地化字符串。
        /// </summary>
        public static string TrafficLimitation_Download {
            get {
                return ResourceManager.GetString("TrafficLimitation_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传和下载 的本地化字符串。
        /// </summary>
        public static string TrafficLimitation_DownloadUpload {
            get {
                return ResourceManager.GetString("TrafficLimitation_DownloadUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        public static string TrafficLimitation_Unlimited {
            get {
                return ResourceManager.GetString("TrafficLimitation_Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流量限制 的本地化字符串。
        /// </summary>
        public static string TrafficLimitationPageTitleText {
            get {
                return ResourceManager.GetString("TrafficLimitationPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流量控制 的本地化字符串。
        /// </summary>
        public static string TrafficMeter {
            get {
                return ResourceManager.GetString("TrafficMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流量控制 的本地化字符串。
        /// </summary>
        public static string TrafficMeterPageTitleText {
            get {
                return ResourceManager.GetString("TrafficMeterPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流量控制 的本地化字符串。
        /// </summary>
        public static string TrafficMeterSettingPageTitleText {
            get {
                return ResourceManager.GetString("TrafficMeterSettingPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电视 的本地化字符串。
        /// </summary>
        public static string tv {
            get {
                return ResourceManager.GetString("tv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定制用户名 的本地化字符串。
        /// </summary>
        public static string txtDeviceName {
            get {
                return ResourceManager.GetString("txtDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址 的本地化字符串。
        /// </summary>
        public static string txtIPAddress {
            get {
                return ResourceManager.GetString("txtIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接速度 的本地化字符串。
        /// </summary>
        public static string txtLinkRate {
            get {
                return ResourceManager.GetString("txtLinkRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAC地址 的本地化字符串。
        /// </summary>
        public static string txtMACAddress {
            get {
                return ResourceManager.GetString("txtMACAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由器型号 的本地化字符串。
        /// </summary>
        public static string txtRoutename {
            get {
                return ResourceManager.GetString("txtRoutename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信号强度 的本地化字符串。
        /// </summary>
        public static string txtSignalStrength {
            get {
                return ResourceManager.GetString("txtSignalStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string txtType {
            get {
                return ResourceManager.GetString("txtType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UNIX PC 的本地化字符串。
        /// </summary>
        public static string unixpc {
            get {
                return ResourceManager.GetString("unixpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传 的本地化字符串。
        /// </summary>
        public static string UploadText {
            get {
                return ResourceManager.GetString("UploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string UserNameText {
            get {
                return ResourceManager.GetString("UserNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本： 的本地化字符串。
        /// </summary>
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请等待一会…… 的本地化字符串。
        /// </summary>
        public static string waitText {
            get {
                return ResourceManager.GetString("waitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本周 的本地化字符串。
        /// </summary>
        public static string WeekAvgText {
            get {
                return ResourceManager.GetString("WeekAvgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本周 的本地化字符串。
        /// </summary>
        public static string WeekTotalText {
            get {
                return ResourceManager.GetString("WeekTotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称/无线网络标识 的本地化字符串。
        /// </summary>
        public static string WiFiName {
            get {
                return ResourceManager.GetString("WiFiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无线设置 的本地化字符串。
        /// </summary>
        public static string WiFiSetting {
            get {
                return ResourceManager.GetString("WiFiSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string WifiSettingsPageTitleText {
            get {
                return ResourceManager.GetString("WifiSettingsPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows PC 的本地化字符串。
        /// </summary>
        public static string windowspc {
            get {
                return ResourceManager.GetString("windowspc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Phone 的本地化字符串。
        /// </summary>
        public static string windowsphone {
            get {
                return ResourceManager.GetString("windowsphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已成功更改无线设置。请使用新的无线设置重新加入无线网络，再登录精灵。 的本地化字符串。
        /// </summary>
        public static string wirelesssettinrelogin {
            get {
                return ResourceManager.GetString("wirelesssettinrelogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改设置会中断无线网络上的活动流量。要继续吗？ 的本地化字符串。
        /// </summary>
        public static string wirelsssetting {
            get {
                return ResourceManager.GetString("wirelsssetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在 NETGEAR 精灵分发内 的本地化字符串。
        /// </summary>
        public static string within_distributionText {
            get {
                return ResourceManager.GetString("within_distributionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string YesButtonContent {
            get {
                return ResourceManager.GetString("YesButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昨天 的本地化字符串。
        /// </summary>
        public static string YesterdayTotalText {
            get {
                return ResourceManager.GetString("YesterdayTotalText", resourceCulture);
            }
        }
    }
}
